const testAdminExerciseResults = [
  {
    id: 1,
    bitSelected: null,
    actualBit: null,
    noErrorsSelected: false,
    actualNoErrors: false,
    twoErrorsSelected: true,
    actualTwoErrors: true,
    correct: true,
    userId: 'auth0|558',
    submittedOn: '2022-01-15-223T18:25:43.511Z',
  },
  {
    id: 2,
    bitSelected: null,
    actualBit: null,
    noErrorsSelected: true,
    actualNoErrors: true,
    twoErrorsSelected: false,
    actualTwoErrors: false,
    correct: true,
    userId: 'auth0|558',
    submittedOn: '2022-01-29-T19:25:43.511Z',
  },
  {
    id: 3,
    bitSelected: 5,
    actualBit: null,
    noErrorsSelected: false,
    actualNoErrors: true,
    twoErrorsSelected: false,
    actualTwoErrors: false,
    correct: false,
    userId: 'auth0|558',
    submittedOn: '2022-01-15-T19:28:43.299Z',
  },
  {
    id: 4,
    bitSelected: 12,
    actualBit: 12,
    noErrorsSelected: false,
    actualNoErrors: false,
    twoErrorsSelected: false,
    actualTwoErrors: false,
    correct: true,
    userId: 'auth0|558',
    submittedOn: '2022-02-16-T18:25:43.511Z',
  },
  {
    id: 5,
    bitSelected: null,
    actualBit: null,
    noErrorsSelected: false,
    actualNoErrors: true,
    twoErrorsSelected: true,
    actualTwoErrors: false,
    correct: false,
    userId: 'auth0|558',
    submittedOn: '2022-01-17-T18:25:43.511Z',
  },
  {
    id: 6,
    bitSelected: null,
    actualBit: null,
    noErrorsSelected: false,
    actualNoErrors: false,
    twoErrorsSelected: true,
    actualTwoErrors: true,
    correct: true,
    userId: 'auth0|558',
    submittedOn: '2022-01-18-T18:25:43.511Z',
  },
  {
    id: 7,
    bitSelected: 5,
    actualBit: null,
    noErrorsSelected: false,
    actualNoErrors: true,
    twoErrorsSelected: false,
    actualTwoErrors: false,
    correct: false,
    userId: null,
    submittedOn: '2022-01-20-T19:28:43.299Z',
  },
  {
    id: 8,
    bitSelected: 12,
    actualBit: 12,
    noErrorsSelected: false,
    actualNoErrors: false,
    twoErrorsSelected: false,
    actualTwoErrors: false,
    correct: true,
    userId: null,
    submittedOn: '2022-01-21-T18:25:43.511Z',
  },
  {
    id: 9,
    bitSelected: null,
    actualBit: null,
    noErrorsSelected: false,
    actualNoErrors: false,
    twoErrorsSelected: true,
    actualTwoErrors: true,
    correct: true,
    userId: null,
    submittedOn: '2022-01-22-T18:25:43.511Z',
  },
  {
    id: 10,
    bitSelected: null,
    actualBit: null,
    noErrorsSelected: false,
    actualNoErrors: false,
    twoErrorsSelected: true,
    actualTwoErrors: true,
    correct: true,
    userId: 'auth0|927Admin',
    submittedOn: '2022-01-23-T18:25:43.511Z',
  },
  {
    id: 11,
    bitSelected: 15,
    actualBit: null,
    noErrorsSelected: false,
    actualNoErrors: false,
    twoErrorsSelected: false,
    actualTwoErrors: true,
    correct: false,
    userId: 'auth0|927Admin',
    submittedOn: '2022-01-24-T19:28:43.299Z',
  },
  {
    id: 12,
    bitSelected: 6,
    actualBit: 6,
    noErrorsSelected: false,
    actualNoErrors: false,
    twoErrorsSelected: false,
    actualTwoErrors: false,
    correct: true,
    userId: 'auth0|927Admin',
    submittedOn: '2022-01-25-T18:25:43.511Z',
  },
];

const testUserExerciseResults = [
  {
    id: 1,
    bitSelected: null,
    actualBit: null,
    noErrorsSelected: false,
    actualNoErrors: false,
    twoErrorsSelected: true,
    actualTwoErrors: true,
    correct: true,
    userId: 'auth0|558',
    submittedOn: '2022-01-15-T18:25:43.511Z',
  },
  {
    id: 2,
    bitSelected: null,
    actualBit: null,
    noErrorsSelected: true,
    actualNoErrors: true,
    twoErrorsSelected: false,
    actualTwoErrors: false,
    correct: true,
    userId: 'auth0|558',
    submittedOn: '2022-01-29-T19:25:43.511Z',
  },
  {
    id: 3,
    bitSelected: 5,
    actualBit: null,
    noErrorsSelected: false,
    actualNoErrors: true,
    twoErrorsSelected: false,
    actualTwoErrors: false,
    correct: false,
    userId: 'auth0|558',
    submittedOn: '2022-01-15-T19:28:43.299Z',
  },
  {
    id: 4,
    bitSelected: 12,
    actualBit: 12,
    noErrorsSelected: false,
    actualNoErrors: false,
    twoErrorsSelected: false,
    actualTwoErrors: false,
    correct: true,
    userId: 'auth0|558',
    submittedOn: '2022-02-16-T18:25:43.511Z',
  },
  {
    id: 5,
    bitSelected: null,
    actualBit: null,
    noErrorsSelected: false,
    actualNoErrors: true,
    twoErrorsSelected: true,
    actualTwoErrors: false,
    correct: false,
    userId: 'auth0|558',
    submittedOn: '2022-01-17-T18:25:43.511Z',
  },
  {
    id: 6,
    bitSelected: null,
    actualBit: null,
    noErrorsSelected: false,
    actualNoErrors: false,
    twoErrorsSelected: true,
    actualTwoErrors: true,
    correct: true,
    userId: 'auth0|558',
    submittedOn: '2022-01-18-T18:25:43.511Z',
  },
];

export { testUserExerciseResults, testAdminExerciseResults as default };
